id: I095096F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:56:38+00:00'
last_modified: '2022-06-08T02:16:36.614523+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5150
  title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    24F3:
      image_group_id: I1KG5166
      title: ''
      total_pages: 62
      order: 1
      base_file: 24F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
