id: P004607
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5150
  title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ་
  author: ''
  volumes:
    e077eb216eb742779fdfeaf58b91dd47:
      image_group_id: I1KG5166
      title: ''
      volume_number: 1
      total_pages: 62
      base_file: v001.txt
