id: P004607
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:06.555046
source_metadata:
  id: bdr:W1KG5150
  title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ་
  author: ''
  volumes:
    e077eb216eb742779fdfeaf58b91dd47:
      image_group_id: I1KG5166
      title: ''
      volume_number: 1
      total_pages: 62
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
